Vagrant.configure("2") do |m|
  [1,2].each do |i|
    
    m.vm.define "es_server_#{i}" do |node|
      
      node.vm.provider :virtualbox do |p|
        p.name = "elasticsearch_cluster_#{i}_#{Time.now.to_i}"
        p.customize ["modifyvm", :id, "--memory", 512, "--cpus",   "1"]
      end
      
      node.vm.box = "precise64"
      node.vm.hostname = "es-node0#{i}"
      node.vm.network "private_network", ip: "192.168.60.1#{i}"

      node.vm.provision :shell, :inline => "sudo apt-get update --fix-missing"
      #rabbit_node.vm.provision :shell, :inline => "sudo apt-get -y install zip"
      #rabbit_node.vm.provision :shell, :inline => "sudo apt-get -y install emacs23-nox"
      #rabbit_node.vm.provision :shell, :inline => "sudo apt-get -y install python-software-properties"
      #rabbit_node.vm.provision :shell, :inline => "sudo mkdir -p /var/chef/cache"
      #rabbit_node.vm.provision :shell, :inline => "sudo sh -c \"echo 'node0#{i}' > /etc/hostname\""
      #rabbit_node.vm.provision :shell, :inline => "sudo hostname -F /etc/hostname"

    end
  end
end